parameters:
  initArgs:

steps:

- task: NuGetAuthenticate@1
  displayName: 🔏 Authenticate NuGet feeds
  inputs:
    forceReinstallCredentialProvider: true

- powershell: |
    $AccessToken = '$(System.AccessToken)' # Avoid specifying the access token directly on the init.ps1 command line to avoid it showing up in errors
    .\init.ps1 -AccessToken $AccessToken ${{ parameters['initArgs'] }} -UpgradePrerequisites -NoNuGetCredProvider
    dotnet --info

    # Print mono version if it is present.
    if (Get-Command mono -ErrorAction SilentlyContinue) {
      mono --version
    }
  displayName: ⚙ Install prerequisites

# Install Java SDK explicitly since we still build for .NET7; see https://stackoverflow.com/questions/77519046/maui-xamarin-build-failing-with-microsoft-android-sdk-tooling-targets20-5/77519051#77519051
- task: JavaToolInstaller@0
  displayName: 'Use Java 17'
  inputs:
    versionSpec: 17
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- powershell: azure-pipelines/variables/_pipelines.ps1
  failOnStderr: true
  displayName: ⚙ Set pipeline variables based on source
  name: SetPipelineVariables
